from core.generated_code import (
    GeneratedCodeError,
    extract_and_validate,
    normalize_generated_math_code,
    proposal_fingerprint,
    validate_generated_math_code,
)


VALID_CODE = """
def dynamics(t, y, args):
    k = args[0]
    return jnp.array([-k * y[0]])

metadata = [
    {'name': 'k', 'range': (0.01, 1.0)}
]
"""


INVALID_CODE = """
def dynamics(t, y, args):
    open('/tmp/bad', 'w').write('bad')
    return jnp.array([0.0])

metadata = [
    {'name': 'k', 'range': (0.01, 1.0)}
]
"""


INVALID_ARGS_CODE = """
def dynamics(t, y, args):
    k = args['k']
    return jnp.array([-k * y[0]])

metadata = [
    {'name': 'k', 'range': (0.01, 1.0)}
]
"""


SAFE_IMPORT_CODE = """
import jax.numpy as jnp

def dynamics(t, y, args):
    k = args[0]
    return jnp.array([-k * y[0]])

metadata = [
    {'name': 'k', 'range': (0.01, 1.0)}
]
"""


DOCSTRING_AND_EXTRA_WHITESPACE_CODE = '''
"generated by model"

import jax.numpy as jnp

def dynamics(t, y, args):
    k = args[0]
    return jnp.array([-k * y[0]])


metadata = [
    {'name': 'k', 'range': (0.01, 1.0)}
]
'''


EXTRA_TOP_LEVEL_ASSIGNMENT_CODE = """
scale = 2.0

def dynamics(t, y, args):
    k = args[0]
    return jnp.array([-k * y[0]])

metadata = [
    {'name': 'k', 'range': (0.01, 1.0)}
]
"""


INVALID_METADATA_RANGE_CODE = """
def dynamics(t, y, args):
    k = args[0]
    return jnp.array([-k * y[0]])

metadata = [
    {'name': 'k', 'range': (1.0, 0.01)}
]
"""


MISMATCHED_METADATA_COUNT_CODE = """
def dynamics(t, y, args):
    k1 = args[0]
    k2 = args[1]
    return jnp.array([-(k1 + k2) * y[0]])

metadata = [
    {'name': 'k1', 'range': (0.01, 1.0)}
]
"""


DANGEROUS_IMPORT_CODE = """
import os

def dynamics(t, y, args):
    return jnp.array([0.0])

metadata = [
    {'name': 'k', 'range': (0.01, 1.0)}
]
"""


def main():
    validate_generated_math_code(VALID_CODE)
    normalized_code, normalization_applied = normalize_generated_math_code(SAFE_IMPORT_CODE)
    assert normalization_applied is True
    assert "import jax.numpy as jnp" not in normalized_code

    docstring_normalized, docstring_normalized_applied = normalize_generated_math_code(
        DOCSTRING_AND_EXTRA_WHITESPACE_CODE
    )
    assert docstring_normalized_applied is True
    assert docstring_normalized.startswith("def dynamics(t, y, args):")
    assert '"generated by model"' not in docstring_normalized
    assert "import jax.numpy as jnp" not in docstring_normalized
    assert docstring_normalized.count("metadata = [") == 1

    extracted = extract_and_validate(f"```python\n{SAFE_IMPORT_CODE}\n```", normalize=True)
    assert extracted is not None
    assert extracted.normalization_applied is True
    assert "import jax.numpy as jnp" not in extracted.code
    assert proposal_fingerprint(SAFE_IMPORT_CODE) == proposal_fingerprint(VALID_CODE)

    try:
        validate_generated_math_code(INVALID_CODE)
    except GeneratedCodeError:
        print("SUCCESS: unsafe generated code was rejected")
    else:
        raise AssertionError("unsafe generated code should have been rejected")

    try:
        validate_generated_math_code(INVALID_ARGS_CODE)
    except GeneratedCodeError:
        print("SUCCESS: dict-style args access was rejected")
    else:
        raise AssertionError("dict-style args access should have been rejected")

    try:
        extract_and_validate(f"```python\n{EXTRA_TOP_LEVEL_ASSIGNMENT_CODE}\n```", normalize=True)
    except GeneratedCodeError:
        print("SUCCESS: extra top-level assignments were rejected")
    else:
        raise AssertionError("extra top-level assignments should have been rejected")

    try:
        validate_generated_math_code(INVALID_METADATA_RANGE_CODE)
    except GeneratedCodeError:
        print("SUCCESS: invalid metadata ranges were rejected")
    else:
        raise AssertionError("invalid metadata ranges should have been rejected")

    try:
        validate_generated_math_code(MISMATCHED_METADATA_COUNT_CODE)
    except GeneratedCodeError:
        print("SUCCESS: metadata count mismatches were rejected")
    else:
        raise AssertionError("metadata count mismatches should have been rejected")

    try:
        extract_and_validate(f"```python\n{DANGEROUS_IMPORT_CODE}\n```", normalize=True)
    except GeneratedCodeError:
        print("SUCCESS: dangerous imports are still rejected after normalization")
        return
    raise AssertionError("dangerous imports should still be rejected after normalization")


if __name__ == "__main__":
    main()
